// AUTO-GENERATED by scripts/gen-promo-timings.mjs — do not edit by hand.
// Scene durations (seconds) + phrase marks (frames, scene-relative) locked to
// the narration take (77.23s total).
export const FPS = 30;
export const NARRATION_SECONDS = 77.23;
export const SCENES = [
  {
    "k": "hook",
    "s": 9.53,
    "marks": {
      "sub": 59,
      "pct": 178,
      "never": 201,
      "brand": 230
    }
  },
  {
    "k": "sweep",
    "s": 13.63,
    "marks": {
      "f0": 68,
      "f1": 121,
      "f2": 164,
      "f3": 232,
      "f4": 285,
      "f5": 318,
      "f6": 356
    }
  },
  {
    "k": "p1",
    "s": 11.55,
    "marks": {
      "chip": 83,
      "priya": 162,
      "fills": 289
    }
  },
  {
    "k": "p2",
    "s": 7.34,
    "marks": {
      "chip": 142
    }
  },
  {
    "k": "p3",
    "s": 8.51,
    "marks": {
      "chip": 189,
      "priya": 140
    }
  },
  {
    "k": "adds",
    "s": 10.89,
    "marks": {
      "chip": 155,
      "show": 279
    }
  },
  {
    "k": "outcome",
    "s": 8.24,
    "marks": {
      "l0": 35,
      "l1": 65,
      "l2": 109
    }
  },
  {
    "k": "cta",
    "s": 7.54,
    "marks": {
      "btn": 120,
      "url": 158
    }
  }
] as const;
export type SceneKey = typeof SCENES[number]['k'];
