// AUTO-GENERATED by scripts/gen-promo-timings.mjs — do not edit by hand.
// Scene durations (seconds) + phrase marks (frames, scene-relative) locked to
// the narration take (74.35s total).
export const FPS = 30;
export const NARRATION_SECONDS = 74.35;
export const SCENES = [
  {
    "k": "hook",
    "s": 10.1,
    "marks": {
      "sub": 63,
      "pct": 188,
      "never": 209,
      "brand": 238
    }
  },
  {
    "k": "sweep",
    "s": 12.25,
    "marks": {
      "f0": 71,
      "f1": 118,
      "f2": 154,
      "f3": 208,
      "f4": 248,
      "f5": 284,
      "f6": 321
    }
  },
  {
    "k": "p1",
    "s": 11.55,
    "marks": {
      "chip": 60,
      "priya": 162,
      "fills": 293
    }
  },
  {
    "k": "p2",
    "s": 7.15,
    "marks": {
      "chip": 137
    }
  },
  {
    "k": "p3",
    "s": 8.26,
    "marks": {
      "chip": 184,
      "priya": 134
    }
  },
  {
    "k": "adds",
    "s": 10.06,
    "marks": {
      "chip": 150,
      "show": 266
    }
  },
  {
    "k": "outcome",
    "s": 8.02,
    "marks": {
      "l0": 32,
      "l1": 64,
      "l2": 104
    }
  },
  {
    "k": "cta",
    "s": 6.95,
    "marks": {
      "btn": 110,
      "url": 147
    }
  }
] as const;
export type SceneKey = typeof SCENES[number]['k'];
